import type { Article } from './articles-types';

export const ARTICLES_B: Article[] = [
  {
    slug: 'mutluluk-uzerine-konusalim',
    title: 'Mutluluk Üzerine Konuşalım',
    category: 'makaleler',
    excerpt:
      'Mutluluk nedir diye sorsam herkes farklı cevap verir. Cevap bireye özgüdür, kişiseldir fakat hayatta en arzuladığımız şeydir de aynı zamanda.',
    date: '18 Nisan 2021',
    readTime: 6,
    theme: 'rose',
    variant: 2,
    content: [
      { t: 'p', text: 'Mutluluk nedir diye sorsam herkes farklı cevap verir. Cevap bireye özgüdür, kişiseldir fakat hayatta en arzuladığımız şeydir de aynı zamanda. Üzerine sayısız kitap yazılmış, seminerlere konu olmuş, psikoloji literatürünün de çokça çalıştığı bir konudur. Dolayısıyla cevap asla kesin değildir elbette. Belki kıyısından bir yerden yakalayıp, konuşmak, duyurmak ve şifalandırmak üzerine sadece yazabilirim, hepsi bu!' },
      { t: 'p', text: 'Mutlu olmak denince aklımıza acının tam ters karşılığı gelir. Mutluluk varsa, acı yoktur; acı varsa mutluluk yoktur. İkisi birlikte asla var olamaz gibi hissederiz. Acı olmadan mutluluğa ulaşamayacağımız gerçeği ruhsal sürecin en temel baş dinamiğidir. Hayatta ilk var oluş anımızda yani doğumda bile annemizle temas edene kadar ağlıyorken nasıl “mutluluk varsa acı yok” diyebiliriz ki? Acı varsa mutluluk vardır. Sadece acıyı kucaklamamız gerekir. Ruhumuzun ve yaralarımızın en sızladığı zamanlarda iyileşmek ve iyileştirmek için bir şansımız vardır. Bedenimiz, ruhumuzun mutluluğa giden kaynağı bize gösteriyordur. Acıya böyle bakarsak gerçek mutluluk gelebilir anca. Kalbimizin hızlı çarptığı, bedenimizin ağrıdığı, ruhumuza karanlık çöktüğü anlarda bir şey bize yol gösteriyordur. Al, burası kanıyor ve gör; gör ki düşün; düşün ki fark et; fark et ki iyileşsin; iyileşsin ki mutlu ol…' },
      { t: 'p', text: 'Bildiklerimizin ne kadar tersi değil mi? Mutluluk bize hep pozitif olmak, negatife odaklanmamak, olumsuz hakkında konuşmamak olarak öğretildi. Bu anca halının altına süpürmek olur. Halınızın altı kirden, pastan dolup taşarken ne mutluluğu yahu!' },
      { t: 'p', text: 'Mutlu olmak için ilk yol kırılmaktan, acımaktan geçer. Kanayan her meselemiz bize onu görme ve sindirme şansı verir. Sindirdiklerimiz ile mutluluğun ilk yoluna çıkacağız.' },
      { t: 'p', text: 'Peki ikinci yol nedir? Bu da herkes için değişir elbette. Ben sadece kliniksel, dilim döndüğünce psikolojik açıdan ve insan olarak aktaracağım ikinci yolu: “Yaratmak-üretmek”. En temel dürtülerimizi düşünelim; örneğin doğum. Neden doğuruyoruz? Evrimsel olan türün devamı durumunu bir kenara bırakarak düşünelim. 9 ay içimizde bir canlıyı besliyoruz, ağrılarımız, bulantılarımız vb. birçok şey oluyor bedenimizde. Hepsi çok keyifli meseleler değil maalesef. Ya da erkekler neden çocukları olsun istiyor?' },
      { t: 'p', text: 'Hayatta elimizden geldiğince bir şey üretmek-var etmek veya yaratmak mutluluğa giden önemli yollardan biridir. Doğum da bu sebeple kişiler için önemlidir. En büyük yaratım meselesidir çünkü. Mutlu olmak için illa doğurmalı ya da çocuk sahibi olmalıyız demek değildir asla bu yazdıklarım, asla! Sadece insan için üretmenin önemini söylemek ve belirtmek isterim. Tüm bu hayat şartlarında üretmek ve yaratmak bizi mutlu kılar. Bir yazı yazmak, bir dernekte yer almak, sokak hayvanlarına kendini adamak, proje yazmak, çocuk yetiştirmek, şarkı yapmak, film çekmek, bitki yetiştirmek vb. bir sürü üretme meselesi mutluluk için önemlidir. İnsan yarattıkça ve ürettikçe iyileşir. Çünkü ürettiğimiz her şey bizimle ilgilidir, bizim yaralarımızla bağlantılıdır, iyileştiricidir. Bu sebeple her insan aynı doğrultudaki üretim aşamalarında yer almaz. Yaratma cesareti kişiyi an’da kılar, yaraları doğrultusunda eyleme geçmeye sebep olur, iyileştirir. Hayatta daha sağlıklı kalabilmek için, şifa için yaratmak-üretmek çok önemlidir. Herhangi bir konuda yaratıcı olmak ve eyleme geçmek ruhsal sağlık ve mutluluk için kıymetli bir aşamadır.' },
    ],
  },
  {
    slug: 'terapi-ne-ise-yarar',
    title: 'Terapi Ne İşe Yarar?',
    category: 'makaleler',
    excerpt:
      'Benim hikâyem dizi olur mu? Psikolog kimdir? Terapi ne işe yarar? Son dönemlerde artan psikoloji temalı diziler destek almak isteyen kişiler için kafa karışıklığı yarattı.',
    date: '25 Nisan 2021',
    readTime: 7,
    theme: 'teal',
    variant: 3,
    content: [
      { t: 'h2', text: 'Benim Hikâyem Dizi Olur mu? Psikolog Kimdir? Terapi Ne İşe Yarar?' },
      { t: 'p', text: 'Son dönemlerde artan psikoloji temalı diziler destek almak isteyen kişiler için kafa karışıklığı yarattı. Çıkan dizilerin gerçek hikâyelerden olması anonim de olsa bireyin mahremiyetini tehlikeye atmakta ve terapi alma arzusu olan kişiler için korku kaynağı olmaktadır.' },
      { t: 'p', text: 'Psikoterapi son derece etik kurallarla çerçevelenmiş, mahremiyetin göz önünde bulundurulduğu bir alandır. Fakat her meslekte olduğu gibi etik ilkeleri göz ardı eden uzmanlar mutlaka vardır.' },
      { t: 'quote', text: 'Bir danışan olarak mahremiyetinizin korunduğundan emin olmak en büyük hakkınız.' },
      { t: 'p', text: 'Seans odaları özel dizayn edilmiş odalardır. Bu odalarda genellikle ses yalıtımı veya ses dağıtıcı müzik sistemi kullanılmaktadır. Konuştuğunuz her şey sadece sizinle terapistiniz arasında kalmak zorundadır. Terapistiniz, kendinize ve başkasına zarar verme ihtimalinizin olması durumunda sadece yetkili mercilere haber verebilir; bu durumda da size mutlaka bilgi vermek zorundadır. Not tutuyorsa bu notları kimsenin erişemeyeceği bir alanda saklamak zorundadır.' },
      { t: 'p', text: 'Terapistiniz akademik bir çalışma yapıyorsa ve sürecinizin bilimsel alana katkı sağlayacağını söylüyorsa sizden izin almak zorundadır. İzin verdiğiniz takdirde kimliğinizi ortaya çıkarmayacak şekilde bilime katkıda bulunabilir.' },
      { t: 'p', text: 'Psikoterapi almaya gittiğiniz kişinin uzmanlığını sorgulamak en temel hakkınız. Maalesef ülkemizde “sahte psikolog” ya da psikoterapi yapma yetkisi olmayan birçok kişi bu alanda faaliyet göstermektedir.' },
      { t: 'h3', text: 'Psikolog Kimdir?' },
      { t: 'p', text: 'YÖK tarafından kabul edilen yurtiçi psikoloji lisans programları ile denkliği YÖK tarafından kabul edilen yurtdışı psikoloji lisans programlarından lisans derecesi ile mezun olan kişiler, psikolog unvanı kullanma hakkı taşımaktadır. Psikologlar, bireyin bireysel ve toplumsal tutum, davranış, düşünme ve duygu durumlarını inceleyen; davranışın ve zihinsel süreçlerin bilimsel tanım ve açıklamalarını temel alan meslek mensuplarıdır.' },
      { t: 'h3', text: 'Klinik Psikolog Kimdir?' },
      { t: 'p', text: 'İlgili üniversitenin Psikoloji bölümünden mezun olduktan sonra, yüksek lisans eğitimini “Klinik Psikoloji” üzerine tamamlayan bireylere verilen ünvandır. Klinik psikologlar psikoterapi yapma yetkinliği olan kişilerdir.' },
      { t: 'h3', text: 'Psikoterapi Nedir? / Neden Terapiye Gidilir?' },
      { t: 'p', text: 'Psikoterapi size, yaşadığınız zorluklar ya da sıkıntılarla ilgili içgörü kazandırmayı, düşünce ve davranışlarınızda değişiklikler meydana getirmek için motivasyonunuzu artırmayı ve bu değişiklikler için uygun yollar bulmanıza yardımcı olmayı amaçlar.' },
      { t: 'p', text: 'Anne rahmine düştüğümüz andan itibaren her gün, her saat “başkasının kıyafetlerini” giymek zorunda kalıyoruz. Annemizin yükleri/kıyafetleri, babamızın yükleri/kıyafetleri, çevredeki diğer bireylerin yükleri/kıyafetleri, toplumsal yükler/kıyafetler… Bu kadar başkalarından bir şeyler almak bize ait olmayan şeyleri üzerimize yapıştırıyor. Pek çoğumuz bu kıyafetlerin farkında bile değiliz. Farkında olamamak, seçimlerimizi neden yaptığımızın nedenini bilmemek; bizi günlük hayatta zorlayan davranışlarda bulunmaya, zorlandığımız duygu durumlarına, ruhsal ve fiziksel hastalıklara sebep oluyor. Sadece bir hayatımız varken bu hayatı bize ait olmayan kıyafetlerle geçiriyoruz. Bazen artık bedenimiz yeter diyor. Panik atak geçiriyor, sivilce çıkartıyor, egzama oluyor, sebebi bir türlü bulunamayan ağrılarla bizi yoruyor. Beden bu kadar farkındayken, bizler nasıl oluyor da kendimize ait bir hayat yaşayamıyoruz? Ya da bunun için çaba sarf etmiyoruz?' },
      { t: 'p', text: 'Terapi size ait olmayan kıyafetleri çıkarmanızı sağlar. Sallanan bir binanın önce tüm odalarını gezip içeridekilerle tanışmanızı, orayı keşfetmenizi, daha sonra o binayı yıkmayı sağlar. Yıkılan bir binanın yerine yeni ve sizin arzuladığınız bir yapı dikilir. Terapi, size ait olmayan kıyafetlerin çıkartıldığı, derinizi, teninizi keşfettiğiniz, bedeninizin ve ruhunuzun şifalandığı bir süreçtir. Terapi gül bahçesi değildir, yeni bir kimlik inşasıdır.' },
    ],
  },
  {
    slug: 'bagirsak-sagligi-ruh-sagligi',
    title: 'Bağırsak Sağlığı = Ruh Sağlığı',
    category: 'makaleler',
    excerpt:
      'Duygularımız bedende yer alır. Hissettiğimiz, deneyimlediğimiz, yaşadığımız her şey bedene yerleşir. Bunu günlük hayatta fark etmeden dile de getiririz aslında.',
    date: '2 Mayıs 2021',
    readTime: 7,
    theme: 'night',
    variant: 0,
    content: [
      { t: 'p', text: 'Duygularımız bedende yer alır. Hissettiğimiz, deneyimlediğimiz, yaşadığımız her şey bedene yerleşir. Bunu günlük hayatta fark etmeden dile de getiririz aslında. “Midemde kelebekler uçuştu”, “işi o kadar yavaş yaptı ki mideme kramplar girdi”, “korkudan felç geçirecektim”…' },
      { t: 'p', text: 'Duygular bu kadar bedende yer alırken, bedenimizden hiç haberimiz olmadan yaşıyoruz. Duygularımızdan da çok kopuk durumdayız. Bu hayatta sadece nefes alıp veriyoruz, çalışıyoruz, çocuk büyütüyoruz; kendimize yabancı, bedenimize yabancı bir şekilde. Çoğu zaman da hiçbir şeyin farkında değiliz; hastalandığımızda kafamız karışıyor, belki anca o zaman durup düşünüyoruz bir şeyleri. Şifayı hep yapay olanda aramaya başlıyoruz, kapı kapı dolaşıyoruz fakat neden hastalandığımızı düşünmüyoruz çoğu zaman…' },
      { t: 'p', text: 'Bedeni dinlemek bize kendi tarihimiz hakkında çok önemli bilgiler verir aslında. Pek çok yere başvurmak, ötekinden ne olduğunu duymaya çalışmak yerine asıl bilgeye — bedene — sormak yeterlidir…' },
      { t: 'quote', text: 'Vücudumuzda her şeyi bilen, bir bilgeyle yaşıyoruz. BAĞIRSAK…' },
      { t: 'p', text: 'Bağırsakların ikinci beyin olduğunu artık duymayan yoktur diye tahmin ediyorum. Fakat gerçek bundan da öte. Bağırsaklar bizzat ruh sağlığının kendisi aslında. Bağırsaklarımız nasıl çalışıyorsa hayatı da öyle yaşıyoruz. Bazen dengesiz (IBS), bazen kontrolsüz (ishaller), bazen aşırı kontrollü (kabızlık), bazen de hiç ne yaptığımızın farkında olmayarak…' },
      { t: 'p', text: 'Hücre hücre bakacak olursak, aslında büyük ölçüde bakterilerden oluştuğumuzu söyleyebiliriz. Vücudumuzda bulunan çoğu bakteri bağırsaklarımızda yaşarlar. Bu bağırsak “mikrobiyomu” sindirim sağlığımızın durumunu belirler ve beynimizin süreçlerini etkiler.' },
      { t: 'p', text: 'Stres altında olduğunuzda, bağırsaklarınızda bakteri toplulukları daha az çeşitlenir ve bağırsaklar, daha fazla sayıdaki zararlı bakteriler tarafından ele geçirilir. İrritabl bağırsak sendromu ve iltihaplı bağırsak hastalıkları gibi problemler, stresle tetiklenir.' },
      { t: 'p', text: 'Duygusal sıkıntı, zihinsel stres ve travma, bağırsaktaki kötü bakterilerin daha fazla çoğalmasına neden olur ve bağırsaklardaki bu kötü bakteriler ise kişinin kötü ruh hali, anksiyete, depresyon, huzursuzluk ve stres karşısında daha az dirençli olabilmesine yol açar.' },
      { t: 'p', text: 'Günlük hayatta hissettiğimiz duygular bağırsaklarımızı derinden etkiler. Bağırsak yapısı gereği “tutma ve bırakma” görevi görürler. Bu işi yaparken hem bedende salgılanan duygusal hormonlardan etkilenirler, hem de ruh halini etkileyecek hormonlar salgılarlar. Bağırsaklarımızın çalışma ritmi bize duygularımız hakkında — hatta çoğu zaman fark etmediğimiz duygular hakkında — önemli bilgi verir.' },
      { t: 'p', text: 'Hayatta ne kadar güvendeyiz? Güvende hissetmek, korkmamak; hayat ritmimiz ve bağırsak ritmimiz için son derece önemlidir. Ne kadar güvende hissediyorsak o kadar “bırakabiliriz”. Güvende hissettiğimizde “kontrol” etme ihtiyacımız azalır. Güvende hissettiğimizde hayat içinde “an”da kalarak, yaşamın ritmine kapılırız. Bağırsaklarımız da tam olarak böyle çalışır. Yoğun korku ve kaygı yaşıyorsak, güvende hissetmiyorsak bağırsaklar da “bırakma” işlevini yerine getirirken zorlanır.' },
      { t: 'p', text: 'Hayat üzerinde “an”da değil, tam tersi olarak savruluyorsak; bizimle ilgili olmayan bir sürü sürecin içindeysek, kendimizi “güçsüz, yetersiz” hissediyorsak, rüzgârda savrulan bir yaprak gibi yaşıyorsak bağırsaklarımız da tam böyle çalışır: “aşırı derecede bırakarak — kontrolsüz”…' },
      { t: 'p', text: 'Yapılan araştırmalar çocukluk döneminde gerçekleşen ve öngörülemeyen kronik stresin, bedenin kendi içinde düşük dereceli bir iltihaplanma sürecini tetiklediğini ortaya çıkarmıştır. Dengesiz ebeveyn tutumu, evde yapı ve sınırların net olmaması, çocuğun kendini güvende hissetmemesi, ani hayat değişimleri, düzensiz hayat vb. gibi durumlar bedenin iltihap yapmasına sebep olmaktadır. Özellikle bağırsak iltihapları günlük hayatı son derece zorlaştıran, hayat kalitesini bozan süreçlerdir.' },
      { t: 'p', text: 'Özetle bağırsak sağlığımız ruh sağlığımızdır. Hayat boyunca hatırlamadığımız, anlamlandıramadığımız pek çok şey vardır; tüm geçmişi anlamak, bugünü şifalandırır. Bilmediğimizi düşündüğümüz her şey için bedene bakmak, onu dinlemek yeterlidir.' },
    ],
  },
  {
    slug: 'guvende-hissetmek-ve-bagirsak-isleyisi',
    title: 'Güvende Hissetmek ve Bağırsak İşleyişi',
    category: 'makaleler',
    excerpt:
      'Tam olarak güvende hissedebilir miyiz? İçinde bulunduğumuz dünyada, içinde bulunduğumuz bedende? Evrende küçücük bir detayken, hayatta çoğu şey üzerinde kontrolümüz yokken…',
    date: '9 Mayıs 2021',
    readTime: 6,
    theme: 'deep',
    variant: 1,
    content: [
      { t: 'p', text: 'Tam olarak güvende hissedebilir miyiz? İçinde bulunduğumuz dünyada, içinde bulunduğumuz bedende? Evrende küçücük bir detayken, hayatta çoğu şey üzerinde kontrolümüz yokken, duygularımıza çok uzakken içinde bulunduğumuz bedende ve dış dünyada güvende hissetmek çok zor.' },
      { t: 'p', text: 'Hayatlarımızı belirsizliğe bırakarak yaşamak zorundayız. Beş dakika sonra ne olacağını bilmiyoruz, içinde bulunduğumuz fiziki koşullar gittikçe zorlaşıyor. Tutunabileceğimiz tek şey “an”. Sadece şu anda varız, sadece şu anda yaşıyoruz ve tam olarak an’ı biliyoruz. Bedenimizin de tam şu an’da olması fiziksel sağlığımız için çok önemli.' },
      { t: 'p', text: 'Bedenin bir hafızası olduğunu artık biliyoruz. Beden hafızasında bir zaman kavramı yok. Bedenimiz tüm zamansızlık içinde biriktirdikleri ile şu an’da yaşıyor. Tüm sistemimiz buna göre çalışıyor, sağlığımız bu doğrultuda şekilleniyor. Beden duyguları hapsediyor, duygular bedende var oluyor. Duygularımız bedenimiz oluyor. Bağırsaklarımızın çalışma ritmi de tam olarak buralarda sağlıklı çalışmaya veya bozulmaya başlıyor. Özellikle bağırsak sağlığı için bedenimiz, duygusal dünyamızda “güvende hissetmemiz” çok önemli. Lütfen güvende hissetmeyi sadece fiziksel tehdit olarak düşünmeyin. Tüm fiziksel koşullar sağlandığında bile insan kendini güvende hissetmeyebiliyor. Son derece güvenlikli evlerde, korumalı sitelerde bile insanlar korku yaşıyorlar. Peki bunun sebebi gerçekten fiziksel bir korku mu? Hayır.' },
      { t: 'p', text: 'Bastırdığımız duygular, üzerini kapattığımız meseleler “korku” olarak arka planda bedenimizi sarmaya başlıyor. Korku, çok hareketli bir duygudur. Bazen hiç korktuğumuzun farkında bile olmuyoruz çünkü korku farklı duyguların arkasına saklanabiliyor. “Korku” bağırsak sağlığını bizzat etkileyen duygulardan.' },
      { t: 'p', text: 'Bağırsaklarımızın en temel işlevi olan “bırakma” eylemi için bedenin güvende olması gerekir. Şöyle düşünelim bir ceylan olsun. Kendi doğal yaşam alanındayken bir anda aslan tehlikesi hissetsin. Bütün bedeni kaçması için hazırlık yapacaktır ve bu hazırlık içinde bırakma-dışkılama yoktur. Tehlike ne zaman geçerse, beden ne zaman sakinleşir ve kendini güvende hissederse o zaman bırakma-dışkılama eylemi gerçekleşecektir. Dışkılama bedenimiz için rahatlama-bırakma eylemidir bu sebeple güvende hissetmek çok önemlidir. Ya da kendi günlük hayatlarımıza bakalım. Bazı insanlar farklı evlerde veya yerlerde dışkılama yapamazlar. Bu ister uzun bir tatil isterse kısa bir misafirlik görüşmesi olsun. Bu görüşmelerde güvende değiller mi? Sorarsak elbette güvendeyiz, her şey yolunda diyeceklerdir fakat biraz önce bedenin zaman ve mekândan bağımsız bir sistemi olduğunu konuştuk. Bu sebeple dışkılayamama eylemi tam şu andaki tatille ilgili değil, kişinin kendi duygusal sistemiyle alakalıdır. Bedenimiz bizim tatilde olduğumuzu bilmez, bunu farklı bir habitat var ve bir tehlike olarak algılar. Bu sebeple duygularımız ne kadar dengedeyse, kendi duygusal dünyamızda arka plandaki duygularımızla ne kadar iş birliği içindeysek, ne kadar farkındalıkla yaşıyorsak o kadar güvendeyiz. Bağırsaklarımız da o kadar “bırakabilir”…' },
      { t: 'p', text: '“Korkudan altına yapmak” durumunu duymuşsunuzdur. Bunu en çok çocuklarda görürüz. Kontrol edilemeyen, stres eşiğini aşan “korku” anında beden üzerindeki kontrolümüzü kaybederiz, kaslar kendilerini bırakır. Burada artık bedenin kendini koruma içgüdüsü yok olur. Tam bir “donma” hali gerçekleşir ve bir anda boşalmalar başlar. Bu sebeple korkudan altına yapma durumu en çok çocuklarda görülür. Çünkü bu küçük bireyler zaten kas kontrolünü tam yapmazlar ve kendilerini içgüdüsel olarak korumayı tam olarak bilmezler. Yetişkinler içinse ciddi fiziksel ve duygusal korku anında bütün kas kontrolü kaybolur…' },
      { t: 'quote', text: 'Bağırsaklarımız öngörülemeyen ve kronik korku duygusundan hoşlanmaz.' },
    ],
  },
  {
    slug: 'sucluluk-yetersizlik',
    title: 'Suçluluk – Yetersizlik',
    category: 'makaleler',
    excerpt:
      'Suçluluk nedir? Tek başına bir duygu mudur? Yoksa içinde yetersizliği, çaresizliği, korkuyu barındıran insanın kendine her fırsatta darbe vurduğu duygular bütünü müdür?',
    date: '16 Mayıs 2021',
    readTime: 6,
    theme: 'terra',
    variant: 2,
    content: [
      { t: 'p', text: 'Suçluluk nedir? Tek başına bir duygu mudur? Yoksa içinde yetersizliği, çaresizliği, korkuyu barındıran insanın kendine her fırsatta darbe vurduğu duygular bütünü müdür?' },
      { t: 'p', text: 'Suçluluk bunu sürekli yanında taşıyan bir insan için hayatın tamamıdır. Diğer duygulardan farklıdır suçlu hissetmek. Sadece hissedilip geçilen bir duygu değildir. Lütfen bir konuda anlaşalım. Herkes ara ara suçlu hisseder fakat bunun hayata yayılması, ilk öncelik duygu olması çok farklı bir şey. Burada bahsedeceğimiz de tam bu hayata yayılan, her alanda suçlu hissetmek…' },
      { t: 'p', text: 'Suçluluk bunu sürekli hisseden insan için bütün hayata yayılır, tercihlere yayılır.' },
      { t: 'quote', text: 'Suçluluğun kardeşleri vardır. En yakını yetersizliktir, dostu korkudur, yoldaşı fazla sorumluluktur, sığındığı liman hayır diyememek-sınır çizememektir.' },
      { t: 'p', text: '“Kendi aramızda konuştuğumuz bende özgüven eksikliği var, ben yapamam ki, hayır diyemiyorum, hayır dememek için her şeyi yapıyorum, benim buna hakkım yok, ben herkese kucak açıyorum, herkese verici davranırım, o üzülmesin diye her şeyi yaptım, ben başkalarını mutlu ederek mutlu olurum, başkalarının yapması gereken şeyleri bile ben üzerime alıyorum” ve daha niceleri… Ortada bir suç, bir hata varsa o her zaman size mi ait? Bu cümleler sizin için tanıdık mı?' },
      { t: 'p', text: 'Bir insan bu kadar yaşanması zor bir duygu bütünü hale nasıl geldi? Sorunun cevabı bugünde değil, çok daha eskilere uzanıyor…' },
      { t: 'p', text: 'Asıl önemli soru bu galiba. Beraber en temele bakalım…' },
      { t: 'p', text: 'Hayata gözlerini yeni açmış küçücük bir bebek var oluşunun değerli olduğunu hissetmeli. Yeni yeni ayaklanmış küçük bir çocuk belli sınırlar içerisinde özgür olduğunu hissedebilmeli. Çocuk hem fiziksel olarak hem ruhsal olarak kendini güvende hissetmeli. Dış yaşamdaki ve ev yaşamındaki olumsuzlukların onunla ilgili olduğunu düşünmemeli. Çocuğun hayatındaki tüm yetişkinlerin kendi sorumluluklarını üstlenmeleri gerekmektedir. Bir birey olarak çocuğun “görülmesi”, “duyulması”, “duygusal ve fiziksel ihtiyacının” karşılanması gerekir.' },
      { t: 'p', text: 'İşte tam buralarda suçluluk oluşmaya başlıyor. Küçük bir çocuk ebeveyni tarafından duygusal ve fiziksel olarak ihmal ediliyorsa, yaşına uygun olarak uyaran verilmiyorsa, bireyselliğine saygı duyulmuyorsa hatta birey olarak görülmüyorsa suçlu hisseder. Bir bebeğe, çocuğa “değerli” hissettirmemek onu suçlu hissettirir. Değerli hissetmemekle suçluluk çok farklı duygular gibi görünse de suçluluk dediğimiz duygu aslında “içe dönmüş öfke”dir. İçe dönmüş öfke kişinin her süreçte kendine öfkelenmesi, hata yapma esnekliğini kendine sunmaması, değerli hissetmemesidir. Hepsi birleşince suçluluk ortaya çıkar. Suçlu hissetmek bir evse bu evin temeli içe dönmüş öfkedir. Evdeki eşyalar ise biraz önce saydığım duygulardır.' },
      { t: 'p', text: 'Hayata yayılan suçluluk kişinin önce kendi değerini öldürür. Kişi kendi hayatındaki en değersiz şey haline gelirken, ötekiler yüceltilmeye başlar. Öfke ötekine çıkmaz, ortada sinirlenecek bir şey olursa kişi kendine kızar. Suçluluk bütün sınırları ortadan kaldırır. Hayır demek, sınır çizmek zorlaşır bazen imkânsız hale gelir. Suçluluk bedene de yansır. Beden gittikçe değersizleşir, kişinin kendi gözünde çirkinleşmeye başlar. Beslenme bozulur, aşırı yemeler veya hiç yememe durumları oluşur. İnsan kendine değer verdiğinde, öfkeyi kendi içine döndürmekten vazgeçtiğinde hem kendi bedenini besler hem de ruhunu.' },
      { t: 'p', text: 'Suçluluk öyle kolay bir duygu değildir.' },
    ],
  },
  {
    slug: 'olumsuz-duygulari-yemek-ya-da-yememek',
    title: 'Olumsuz Duyguları Yemek ya da Yememek — İşte Bütün Mesele Bu!',
    category: 'makaleler',
    excerpt:
      'Olumsuz duygular denilince aklınıza neler geliyor? Sizin için deneyimlenmesi, yaşantılanması veya üzerine konuşulması en zor duygular hangisi?',
    date: '23 Mayıs 2021',
    readTime: 4,
    theme: 'sand',
    variant: 3,
    content: [
      { t: 'p', text: 'Olumsuz duygular denilince aklınıza neler geliyor? Sizin için deneyimlenmesi, yaşantılanması veya üzerine konuşulması en zor duygular hangisi?' },
      { t: 'p', text: 'Bu duyguları “olumsuz” yapan şey nedir? Bunlar üzerine konuşalım…' },
      { t: 'p', text: 'Herkes için “olumsuz duygu” farklı şekilde algılanır. Kimi öfkeyi olumsuz bulur, kimi üzüntüyü, kimi kaygıyı, belki mutluluğu…' },
      { t: 'p', text: 'Duygular bedenimizdeki organlarımız gibidir. Hepsinin çok temel işlevleri ve anlamları vardır. Kalbiniz olmadan yaşayamayacağınız gibi olumsuz olarak deneyimlediğiniz duyguları da yaşantılamadan “yaşayamazsınız”. Tabi ruhsal olarak. Ne demektir bu? Olumsuz olarak adlandırdığınız duyguları deneyimlemek istememek demek, kalbinizin atışını durdurmaya çalışmanız, bağırsaklarınızın işleyişini bozmaya çalışmanız demektir. Bedenimiz nasıl bir ahenk içinde çalışıyorsa, ruhumuz da aynı işleyişe sahiptir. Her duygunun beyinde, bedende ve bilinçdışında bir görevi vardır. Deneyimlemekten kaçtığımız olumsuz duygular ruhumuzun işleyişini bozmaya başlar. Bizler farkında olarak veya olmayarak bu bozulan işleyişe karşı bir şeyler yapmaya çalışırız. Başımız ağrıdığında ağrı kesici alabiliriz, temiz hava almayı deneyebiliriz, su içmeyi düşünebiliriz, tatlı yemek isteyebiliriz. Gördüğünüz gibi baş ağrısını dindirmek için birçok farklı yol var ve her yol aynı şekilde işlevsel değil. Olumsuz duyguları yaşamamak için de birbirinden farklı yollar deneriz fakat genellikle bunların farkında olmayız çünkü bilinç seviyesinde değildir.' },
      { t: 'p', text: 'Duygusal yeme atakları olumsuz duyguların deneyimlenmesi için en çok başvurulan “işlevsiz” yollardan biridir. Kişi genelde bunu “stres yapınca yemek yerim” şeklinde ifade etse de arka planda stresten öte çok daha farklı duygular ve dinamikler söz konusudur.' },
      { t: 'p', text: 'Karbonhidrat, şeker ve yağ oranından fazlasıyla zengin besinlerin beyinde salgıladığı hormonlar sayesinde deneyimlenmekten çekindiğimiz duygular bastırılır. Bu bastırma süresi kısa sürelidir. 5 dakika ile bir saat arasında değişir. Tam bu noktada hormon etkisi geçtiğinde kişi tekrardan bir yeme atağı geçirmeye başlar. Arkasından büyük bir suçluluk hissi de genellikle eşlik eder… Olumsuz duyguları deneyimlemekten kaçmak ve bastırmak, duygusal yeme atağı gibi pek çok işlevsiz baş etme yöntemlerini getirir.' },
    ],
  },
  {
    slug: 'ilk-bag',
    title: 'İlk Bağ',
    category: 'makaleler',
    excerpt:
      '“Ben kimseye bağlanamıyorum”, “ben herkese hemen bağlanıyorum”, “ait hissetmiyorum hiçbir yere”… Bağlanma hayatımızın her alanını derinden etkiler.',
    date: '30 Mayıs 2021',
    readTime: 6,
    theme: 'teal',
    variant: 4,
    content: [
      { t: 'p', text: '“Ben kimseye bağlanamıyorum”, “ben herkese hemen bağlanıyorum”, “ait hissetmiyorum hiçbir yere” vb. gibi söylemleri duymuşsunuzdur veya üzerine o kadar çok dizi-film çekildi ki mutlaka izlemişsinizdir. Nedeni üzerine de az çok fikriniz vardır. “Bağlanma bozukluğu” diye bağırır birçok kaynak. “Bende bağlanma bozukluğu var” diye de espri yaparız hatta. Kulağa çok önemli gelmeyen bir kavram gibi geliyor fakat öyle derin bir mevzu ki “bağlanma” hayatımızın her alanını derinden etkiler. İş yaşantımızı, partnerimizle olan ilişkimizi, çocuklarımızla olan ilişkimizi, hayatta köklenmemizi, yaşayış şeklimizi, bedenimizi, kilo durumumuzu vb. alanı çok derinden etkiler. Bu kadar önemli mesele olan “bağlanma” nasıl gelişiyor veya sağlıklı gelişemiyor ona bakalım.' },
      { t: 'p', text: 'Bağlanmanın ilk basamakları henüz anne rahmine bile düşmeden gelişiyor aslında. Annemizin kendi annesi ile olan bağlanması nasılsa, kendi yaralarını iyileştirmeden bizimle de öyle bağ kuracaktır. Daha sonraki kısım gebelik sürecini planlarken oluyor. Tabii ki planlıysa… Gebeliğe psikolojik hazırlık bu anlamda çok önemli. Bir bebeği arzulamak, onu zihinde tasarlamak, üzerine konuşmak, fiziksel ve psikolojik olarak hazırlık yapmak; benim yazarken sizin de okurken yüzünüzde hafif bir gülümseme olmuştur illa ki… Beden kayıtlarımız bütün bunları tek tek yazıyor ve bebekler bu beden kayıtlarının tam içine düşüyorlar. Biliyorlar dolayısıyla isteniyorlar mı? Arzulanıyorlar mı? Bekleniyorlar mı? Bağlanma süreci ilmek ilmek işlenmiş oluyor.' },
      { t: 'p', text: 'Sonra gebelik süreci geliyor. Bebek, annenin rahminde kısa bir süreliğine misafir. Bu misafir her şeyi duyuyor, hissediyor, fikir sahibi oluyor. Kalıcı olarak geleceği ortam hakkında, ebeveynleri hakkında çok önemli bilgiler ediniyor. Bu bilgiler bağlanma sürecine önemli katkılarda bulunuyor. Annenin bebeği ile sesli bir şekilde konuşması, ona seslenmesi bebek için öyle önemli bir detay ki… Yabancı bir yerde misafirsiniz ve ev sahipleri sizinle sohbet ediyorsa, sizi arzuluyorsa, ortam güvenli ve keyifliyse onlarla sıcacık bağlar geliştirirsiniz. Anneniz gebelik boyunca sizinle hiç konuşmuyorsa, ortam güvensiz, sesler huzursuz, belki şiddet varsa korkar, o eve gelmek istemez, huzursuz olursunuz. Korkulu bir bağlanma oracıkta hemen gelişir.' },
      { t: 'p', text: 'Diğer önemli durum ise “doğum”… Doğum bir yolculuktur. Bebeğin evine yolculuğu, bebeğin ailesine yolculuk. Doğum bir şölendir, doğum yeryüzündeki en mucizevi olaydır. Acaba bu yolculuğumuz nasıl oluyor? Bu yolculukta bebeğe, anneye saygı duyuluyor mu? Bebeği bu yolculuğa çıkarken hissettikleri çok önemli. Ortamda nasıl bir hava var? Sesler nasıl? Mahremiyet var mı? Her memeli mahremiyet olan bir ortamda doğmak ve doğurulmak ister. Sevgi var mı bu yolculukta? Eve giden uçakta hostesler güler yüzlü mü? Yolcularla konuşuyor mu? Onlara güzel yiyecek-içecek ikram ediyor mu? Bebek için bu yolculuktaki bindiği öyle önemli ki. Doğum ekibi nasıl? Güler yüzlü mü? Anneyi ve yolcu bebeği sevgi ile karşılıyor mu? Yolcu iner inmez annesiyle buluşturulacak mı? Ne kadar büyük kaygılar küçücük bir bebek için ve ne kadar önemli meseleler bebek için, bebeğin hayatta-annesiyle bağ kurması için.' },
      { t: 'quote', text: 'Kurulamayan her bağ, güvenli bağlanamayan her bebek önce kendi için sonra toplum için derin bir yara…' },
    ],
  },
  {
    slug: 'gebelik-surecinde-ve-dogum-aninda-psikolojik-destek',
    title: 'Gebelik Sürecinde ve Doğum Anında Psikolojik Destek',
    category: 'freyada-dogum',
    excerpt:
      'Gebelik sürecinde psikolojik destek ülkemiz için yeni bir kavramdır. Son dönemdeki çalışmalar gebelik döneminde ve doğum zamanında psikolojik destek almanın, doğum sonrası depresyon oranlarını ciddi şekilde azalttığını göstermektedir.',
    date: '31 Ocak 2023',
    readTime: 4,
    theme: 'terra',
    variant: 0,
    content: [
      { t: 'p', text: 'Gebelik sürecinde psikolojik destek ülkemiz için yeni bir kavramdır. Son dönemdeki çalışmalar gebelik döneminde ve doğum zamanında psikolojik destek almanın, doğum sonrası depresyon oranlarını ciddi şekilde azaltmakta ve anne-bebek bağlanmasını kolaylaştırmakta olduğunu göstermektedir.' },
      { t: 'p', text: 'Dünyaya bir çocuk getirmek kişinin kendi travmalarının, çocukluk yaşantılarının tekrardan gün yüzüne çıkmasına neden olur. Bu yaşantılar genelde “bilinç seviyesinde” gün yüzüne çıkmamaktadır. “Bilinçdışı” unsur dediğimiz dolaylı süreçlerle hayatımızı etkiler. Bazen bedensel olarak rahatsızlık yaratır, bazen rüyalar ile karşımıza çıkar, bazen ani duygu değişimleri gibi pek çok açıdan hayatımızda varlığını sürdürür. Ebeveyn olma yolculuğunda bize ait olmayan pek çok kıyafet üzerimizde vardır, bizi terletir, ağırlık yapar, yorar. Bu süreçteki psikolojik destek bize ait olmayan kıyafetlerin çıkartılması, travmaların çalışılması ve bebekle sağlıklı bağ kurmayı içerir.' },
    ],
  },
  {
    slug: 'dogum-surecimiz-hayatimizin-geri-kalanini-belirliyor',
    title: 'Doğum Sürecimiz Hayatımızın Geri Kalanını Belirliyor',
    category: 'freyada-dogum',
    excerpt:
      'Bu hayata gelirken nasıl bir yolumuz oldu acaba? Arzulanan bir bebek olarak mı geldik yoksa sürpriz bir bebek olarak mı? Keşke bir önemi olmasaydı…',
    date: '31 Ocak 2023',
    readTime: 5,
    theme: 'rose',
    variant: 1,
    content: [
      { t: 'p', text: 'Bu hayata gelirken nasıl bir yolumuz oldu acaba? Arzulanan bir bebek olarak mı geldik yoksa sürpriz bir bebek olarak mı? Belki içinizden “ne önemi var canım” diyorsunuzdur? Keşke bir önemi olmasaydı…' },
      { t: 'p', text: 'Bulunduğunuz şehirden bambaşka bir ülkeye gideceksiniz. Dilini bilmediğiniz, insanlarını tanımadığınız bir ülkeye. Hiçbir fikriniz yok bu ülkeyle ilgili. Sadece bir ailenin yanında kalacağınızı biliyorsunuz, hepsi bu.' },
      { t: 'p', text: 'İlk seçenek şu; bu aile sizin gelmenizi dört gözle bekliyor. Sizi merak ediyor, dilinizi konuşmak için birkaç kitap karıştırıyor, videolar izliyor, kurslara gidiyor. Çok heyecanlılar. Ara ara size telefon açıyorlar, dilleri döndükleri kadar sizinle konuşuyorlar. Yola çıkarken nasıl hissedersiniz? Bu ailenin yanına giderken peki?' },
      { t: 'p', text: 'İkinci seçenek şu; bir ailenin yanına gideceksiniz fakat sizinle hiç iletişim kurmadılar. Siz onların dilini bilmiyorsunuz, onlar da sizin. Tabi hazırlık yapıyorlar elbette. Evlerine yeni birileri gelecek sonuçta fakat bu bilgi onlar için sürpriz olmuş. Daha sonra alışmışlar bu fikre ve sizi kabul etmişler. Bu aileye giderken nasıl hissedersiniz?' },
      { t: 'p', text: 'Doğum da tam böyledir işte. Bizler de dilini hiç bilmediğimiz bir ülkeye ve aileye geldik. Bizi ne kadar arzuladıkları, bizimle yolculuk sürecinde iletişim kurup kurmadıkları, yolculuğun nasıl geçtiği, bizim için çaba gösterip-göstermedikleri öyle önemli ki. Önemli çünkü bu ülke, aile ve ev hakkındaki ilk izlenimimiz. Kendimizi güvende hissetmemizi, ortama ve aileye olan bakışımızı, psikolojimizi ve bedenimizi derinden etkiler.' },
      { t: 'p', text: 'Dünya’ya gelmiş her bebeğin “güvene” ihtiyacı vardır. İlk güven duygusu anne rahmindeyken başlar. Bebek, anne rahmindeyken dış ortamı duyar, hisseder; annesi-ailesi ve ev hakkında bilgi edinir. Annesinin, diğer ev sahiplerinin onunla iletişimi çok önemlidir, böylece bebek kendini güvende hisseder. Ebeveyni ile ilgili bağ geliştirir. Hayat ile olan bağımız anne rahmindeyken başlar. Dünya’ya gelirken yaşadığımız yolculuk sonraki süreçleri derinden etkiler.' },
      { t: 'p', text: 'Her bebeğin çok keyifli bir yolculuğu olmasını dilerim…' },
    ],
  },
  {
    slug: 'lohusa-psikolojisi-ve-lohusaya-destek',
    title: 'Lohusa Psikolojisi ve Lohusaya Destek',
    category: 'freyada-dogum',
    excerpt:
      'Lohusa kelimesi Rumca dilinden Türkçe’mize geçmiştir. Lohusalık literatürde “annelik hüznü” olarak da geçmektedir. Ayrılıkla kavuşmanın iç içe yaşandığı cayır cayır bir dönemdir.',
    date: '31 Ocak 2023',
    readTime: 6,
    theme: 'night',
    variant: 2,
    content: [
      { t: 'p', text: 'Lohusalık psikolojisine geçmeden önce kelime anlamına bir bakalım. Lohusa kelimesi, dilimizde oldukça kullanılan kelimelerden birisidir. Lohusa, Rumca dilinden Türkçe’mize geçmiştir. TDK’ye göre lohusa kelimesi anlamı şu şekildedir: yeni doğum yapmış kadın demektir. Lohusalık literatürde “annelik hüznü” olarak da geçmektedir.' },
      { t: 'p', text: 'Lohusalık, ayrılıkla kavuşmanın iç içe yaşandığı, bedenin inanılmaz derece hem fiziksel olarak hem de psikolojik olarak ateşlendiği, kadının yepyeni bir hayatın kucağına atladığı, yorulduğu, bilinçdışı süreçlerin ortaya çıktığı cayır cayır bir dönemdir. Bazen bir yas sürecini de içinde barındırır. Yeni bir hayata geçiş, eskiyi geride bırakmak demektir. Bazen lohusalık bir anlam kaybıdır. Tüm bu süreçlerde beden kendini onarmaya çalışır, hormonlar dans eder.' },
      { t: 'p', text: 'Kolay değildir içeride bir bebek büyütmek ve önce ondan ayrılmak, sonra onunla tekrar kavuşmak… Doğum aslında bir ayrılık deneyimidir. İçeride büyüttüğünü dışarı çıkarmak için önce onu içeriden ayırmak gerekir. Kavuşmak için ayrılıkların gerektiği gibi…' },
      { t: 'p', text: 'Ayrılığın olduğu her yerde mutlaka hüzün vardır. Doğum bir kavuşma dahi olsa, annenin gebelikten ayrıldığı, içinde taşıdığı bebekten ayrıldığı, eski hayatından ayrıldığı, rutinlerinden ayrıldığı bir süreçtir. Her kadının bu ayrılık serüvenine karşı tepkisi farklı olacaktır. Bu sebeple taze annenin hüznünü kucaklamak ve onun duygularını anlamak için alan açmak çok önemlidir.' },
      { t: 'p', text: 'Özellikle bizim kültürümüzde lohusa kadın tek başına bırakılmaz, etrafında, evinde ona destek olmak için pek çok kişi yer alır. Buralarda yeni hayatına adapte olmaya çalışan anne için “mahremiyet” çok hayatidir. Her alanda onun mahremiyetini düşünmemiz gerekir. Onun onayını almadan, rızasını sormadan bizler için iyilik dolu olsa bile pek çok şeyden uzak durmak önemlidir.' },
      { t: 'p', text: 'Lohusaya destek için yapılan ve atılan çoğu adım aslında yeni anne için zorlayıcı olabilir. Bu sebeple pek çok şey hakkında uzun uzun düşünmek gerekir.' },
      { t: 'p', text: 'Lohusa bir kadına sağlayabileceğimiz en önemli destek onun işlerini kolaylaştırmaktır, bebeğe bakmak değildir. Günlük işleri yapmak, yemek hazırlamak, belki evi toplamak gibi…' },
      { t: 'quote', text: 'Bebek ve bebek bakımı hakkındaki fikirlerimizi de kendimize saklamalıyız. Bebek hakkında iyi ve kötü yaptığımız her yorum taze anne için yaralayıcı olabilir…' },
    ],
  },
  {
    slug: 'sevgili-ebeveyn',
    title: 'Sevgili Ebeveyn',
    category: 'freyada-dogum',
    excerpt:
      'Yeter miyiz? Diye düşündüğün her an, bir çocuk için önemli olan şeyin “koşulsuz sevgi” olduğunu bil.',
    date: '31 Ocak 2023',
    readTime: 4,
    theme: 'terra',
    variant: 4,
    content: [
      { t: 'p', text: 'Yeter miyiz? Diye düşündüğün her an, bir çocuk için önemli olan şeyin “koşulsuz sevgi” olduğunu bil.' },
      { t: 'p', text: 'Nasıl davranmalıyım? Diye düşündüğün her an bir zamanlar çocuk olduğunu hatırla.' },
      { t: 'p', text: 'Nasıl anlayacağım? Diye düşündüğün her dakika bedenindeki bilgiye güven.' },
      { t: 'p', text: 'İhtiyaç duyduğun bilgi sende var. Bugün bir çocuk sahibi olmak için çıktığın yoldan çoktan geçtiğini, hatta o yolu bir çocuk olarak geçtiğini hatırla.' },
      { t: 'p', text: 'Kendi yaralarını, kendi geçmişini hatırla. Asıl bilgi orada. Nasıl sevilmek istediğini, neye ihtiyacın olduğunu hatırla. Önce sen kendi geçmişindeki çocuğu gör, bil ve hatırla ki bugün bedeninde büyüttüğün şifalansın.' },
      { t: 'p', text: 'Koşulsuz sevmeye hazırlan. Bir canlıyı bugün ve tüm gelecekte şefkatle, sımsıcak ve kabul ederek sevmeye hazırlan. Kim olacağını merak ederek, neyi sevip sevmeyeceğini merak ederek, onu arzuyla düşün. Tasarlama… Onu kendin için tasarlama. Sadece arzula. Bu arzu ve merak bedeninden bebeğine geçecek. Kalbini ona olan sevginle doldur. Bu sevgiyi bilerek gelecek sana. Lütfen bedenine yatırım yap. Senin bedenine yaptığın sağlıklı her yatırım bebeğin için şifa olacak. Ve ona sor. Ne istediğini, nasıl bir doğum istediğini mutlaka ona sor. Bu onun doğumu, bu onun doğum günü olacak…' },
    ],
  },
];
