import type { Article } from './articles-types';

export const ARTICLES_A: Article[] = [
  {
    slug: 'terapi-ya-da-sifa',
    title: 'Terapi? Ya da Şifa?',
    category: 'makaleler',
    excerpt:
      'Terapi nedir? Değişim, dönüşüm, yenilenmek? Yıkılmak, derinleşmek, fark etmek? Belki hepsi belki hiçbiri.. Değişmektir belki de terapi, yenilenmek, şifa bulmaktır.',
    date: '7 Şubat 2021',
    readTime: 3,
    theme: 'teal',
    variant: 0,
    content: [
      { t: 'p', text: 'Terapi nedir? Değişim, dönüşüm, yenilenmek? Yıkılmak, derinleşmek, fark etmek? Belki hepsi belki hiçbiri..' },
      { t: 'p', text: 'Değişmektir belki de terapi, yenilenmek, şifa bulmaktır. İyi de nasıl yenileneceğiz yıkılmadan? Terapi yıkılmaktır aynı zamanda. Farkına vararak yıkılmak, yıllarca öyle ya da böyle inşaa ettiğiniz yapının yavaş yavaş tüm katlarının yıkılmasıdır. Yıkmak gerekli midir? Yıkmadan yenilenemez mi? Belki dışı ya da içini yıkmadan nasıl yenileyeceğiz?' },
      { t: 'p', text: 'Korkma diyor uzaktaki bir ses, korkma, yıkılacaksın ama güvende olacak temellerin, kontrolsüz değil hiçbir şey, hızlı gidersen tutacak seni bir el.. Korkma! Güvendesin, öyle bir güvendesin ki burada yargılanmak yok, eleştirilmek yok. Hatta sana daha önce hiç deneyimlemediğin yeni bir tattan da bahsedeyim. Burada sadece sen olduğun için sevileceksin, kabul görüleceksin! Ve bir yerde bunun keyfine öyle bir varacaksın ki sen yıkacaksın ellerinle her bir katı, tane tane bazen hızlı bazen yavaş, bazen gözyaşlarıyla bazen kahkaha atarak! Sen de gönüllü olacaksın bu değişime yenilenmeye.' },
      { t: 'p', text: 'Şifalanacaksın ve sakın bunun tek taraflı olduğunu düşünme, şifa vereceksin aynı zamanda. Senin yenilenmen umut verecek, güç verecek karşındakine ve o senden aldığı gücü başkasına iletecek. Sen sanacaksın ki sadece ben yaşadım. Hayır! Sen upuzun bir şifa zincirinin ilk halkası olacaksın.' },
      { t: 'p', text: 'Yenilenecek, ağlayacak, dönüşecek ve dönüştüreceksin..' },
    ],
  },
  {
    slug: 'cocuklari-nasil-daha-iyi-anlariz',
    title: 'Çocukları Nasıl Daha İyi Anlarız?',
    category: 'makaleler',
    excerpt:
      'Ebeveynlerin ortak söylemi “çocuğum bana hiçbir şey söylemiyor, okulda ne yaşadığını arkadaşlarından duyuyorum”. Peki çocuklar neden ebeveynlerine yaşadıkları en sıradan olayları bile anlatmıyorlar?',
    date: '14 Şubat 2021',
    readTime: 4,
    theme: 'terra',
    variant: 1,
    content: [
      { t: 'p', text: 'Ebeveynlerin ortak söylemi “çocuğum bana hiçbir şey söylemiyor, okulda ne yaşadığını arkadaşlarından duyuyorum”. Peki çocuklar neden ebeveynlerine yaşadıkları en sıradan olayları bile anlatmıyorlar?' },
      { t: 'p', text: 'Konu çocuk olduğunda bizler hep kendi açımızdan bakarız olaylara. Peki şöyle yapalım, kendinizi düşünün bir yetişkin olarak. Siz yaşadıklarınızı kiminle paylaşıyorsunuz? En sıradan, en basit olayları bile birine anlatırken temel kriterleriniz neler? Anlaşılmak, yargılanmamak, güvende hissetmek, destek bulmak… Biz yetişkinler bunları arıyoruz paylaşım yaparken. Peki çocuklarımıza bunları sağlıyor muyuz? Bir yetişkin olarak her şeyi bildiğimizi düşünüp onlara sadece nasihat mi veriyoruz ya da başka şeylerle mi ilgileniyoruz? Tüm bunlar olurken çocukların gelip bize deneyimlerini anlatmaları mümkün değildir. Anlaşılmadığını hisseden çocuk diline ket vurur.' },
      { t: 'h3', text: 'Peki ya nasıl dinleyebiliriz çocukları?' },
      { t: 'ol', items: [
        'Öncelikle tüm uyaranlardan uzaklaşarak. “Şu anda sadece sen ve ben varım. Diğer şeyler umurumda değil. Sadece senin için buradayım. Seni dinlemek ve anlamak için.” Mesajını vermek gerekir.',
        'Bedeni okumak. Anneler-babalar bilirler ki her duygu çocukta başka bedensel tepki yaratır. Kiminin heyecanlanınca yanakları kızarır, kiminin sinirlenince hareket hızı artar, kimi üzülünce içe kapanır. Bu dolaylı mesajları iyi gözlemlemek ve yansıtmak gerekir. Hiçbir telkinde bulunmadan, uzun uzun soru sormadan sadece ve sadece onu iyi gözlemek ve anladığınızı hissettirerek geri bildirim vermek. “Yanakların kızarmış, sanırım bugün canını sıkan bir şey oldu. Çok hareketlendiğini görüyorum, seni birileri kızdırmış olmalı. Elindeki resim çok renkli görünüyor, galiba bugün okulda boyama etkinliği yaptınız.” Duyguları yansıtmak hem çocuğa anlaşıldığının mesajını verirken hem de onun uzun uzun anlatmasını sağlar.',
        'Çocuklar iyi gözlemcilerdir. Ben şimdi bunu anlatırsam bana kızar mı? Benim yanımda olur mu? Beni cezalandırır mı? Diye sürekli ebeveynleri gözlemlerler. Ebeveynin davranışları eğer güven vermiyorsa, çocuk yaşadığı şeyi annesine-babasına anlatamaz.',
      ] },
    ],
  },
  {
    slug: 'obezite-sadece-durmadan-yemek-midir',
    title: 'Obezite, Sadece Durmadan Yemek Midir?',
    category: 'makaleler',
    excerpt:
      'Günümüzde obezite yaygın bir sağlık sorunu olarak görülmektedir. Obezite vücut yağ oranının artışı olarak tanımlanmakta ve en yaygın haliyle beden kitle indeksi ile değerlendirilmektedir.',
    date: '21 Şubat 2021',
    readTime: 9,
    theme: 'night',
    variant: 2,
    content: [
      { t: 'p', text: 'Günümüzde obezite yaygın bir sağlık sorunu olarak görülmektedir. Obezite vücut yağ oranının artışı olarak tanımlanmakta ve en yaygın haliyle beden kitle indeksinin (BKİ) hesaplanması (BKİ=kilo(kg) / boy(m²)) ile değerlendirilmektedir. Beden kitle indeksinin 18,5-25 kg/m² arasında olması sağlıklı kilo anlamına gelirken, BKİ’nin 25-30 kg/m² olması olası artmış risk, BKİ’nın 30 kg/m² ve üstü olması obezite anlamına gelmektedir.' },
      { t: 'p', text: 'Dünya Sağlık Örgütü verilerine göre, dünyada 1 milyardan fazla kilolu insan bulunuyor. Türkiye’de ise kadın nüfusunun yaklaşık üçte biri, erkek nüfusunun da yaklaşık beşte biri obez. Son verilere göre ülkemizde obezite yaygınlığı 30 yaş üzeri erkeklerde %21, kadınlarda ise %43.' },
      { t: 'p', text: 'Obezite tedavisinde pek çok yöntem kullanılmasına rağmen obezite yaygınlığı gün geçtikçe artmakta. Bu durum bize tedavi sürecinde sadece fiziksel belirtilere odaklanmanın yetersiz kaldığını ve kişiyi sürekli yemeğe iten şeyin, yani altta yatan faktörlerin anlaşılması kapsamında yeni tedavi/terapi süreçlerine götürmüştür. Özellikle obezite tedavisinde uygulanan “kilo alma-kilo verme” odaklı mekanik yaklaşımlar, kişinin özellikle süreç başında istenilen şekilde kilo kaybı olmazsa motivasyonun yitirilmesine sebep olurken aynı zamanda verilen kiloların tekrardan geri alınmaya eğilimli olduğu gözlemlenmektedir.' },
      { t: 'p', text: 'Tedavi/terapinin asıl amacının kişinin “kiloya odaklanması” değil, obeziteye neden olan psikolojik faktörlerin keşfedilmesini sağlamak olmalıdır. Bunları keşfeden kişi kilosuna odaklanmak yerine, değiştirmesi gereken şeyler ile ilgili yaratıcılığını ve esnekliğini kullanma becerisine sahip olacaktır.' },
      { t: 'p', text: 'Hayat akıp giderken dünyaya geldiğimiz anlardan itibaren sahip olduğumuz çeşitli roller vardır. Bu rollerin içindeyken de yerine getirmemiz gereken temel görevler, hayattan ve çevremizden beklentilerimiz aktif olarak devrededir ve her evreyi, her rolü takılmadan, travmatize olmadan atlatmamız gerekmektedir. Obezitede ise roller beden üzerine toplanıp hapsolmuştur. Kişi en erken dönemde sadece “yiyen, emen, memeye muhtaç olan” rolünde saplanıp kalmıştır. Hissedilen tüm duygular — öfke, sevinç, acı vb. — bedene yani “yiyen” rolüne bastırılır. Duygu ve beden ayırt edilemez parçalar halinde birbirine dolanmış bir hale gelir.' },
      { t: 'p', text: 'Obez bireyler zevkin gecikmesinden rahatsız olurlar, hazzı erteleyemezler. Hazzın ertelenmesine karşı gösterilen tolerans erken dönemde anne-bebek ilişkisinde öğrenilir veya öğrenilemez bir tablo halini alır.' },
      { t: 'p', text: 'Beslenme/meme emme hazzının ertelenmesi ve bebeğin bu dönemde sakinleştirilebilmesi “anne”ye bağlıdır. Bebek meme istediğinde, biyolojik saatinin fark edilmesi ve gerek duyulmayan emme davranışı isteği karşısında bebeğin tensel temasa ihtiyacının olabileceğinin düşünülmesi, bebeğin ihtiyaçlarının karşılanıyor olması gerekmektedir. Annenin, bebeğin biyolojik ihtiyaçlarını fark etmeyip bebeğin her haz arayışında ona meme ile karşılık veriyor olması kişinin duygularını “yemeğe gömmesine” neden olur. Bebek, yemeğin dış dünya ile bağ olduğunu, sakinleştirme aracı olduğunu ve kolayca ulaşılabilir boyutta olduğunu fark ettiği durumda kendini “aşırı yemekten” koruyan tüm kontrolleri kaybeder.' },
      { t: 'p', text: 'Erken dönemde bebeğin, kendi ile dış dünya arasındaki ayrımı fark etmeye başlamasıyla birlikte sosyalleşme gerçekleşir. Sosyalleşme peşinden “ötekilerin” bakışını fark etmeyi ve bedenle ilgili fikirlerin oluşmasını sağlar. Bebeğin ilk sosyalleştiği kişi kendisine “bakım” veren annesidir. Annenin bebeği bütün olarak algılamaması, ona tiksindirici, kusurlu, düzeltilmesi gereken, donuk ve fark etmeyen gözlerle bakması ilk sosyalleşme deneyimini sekteye uğratır. Obez bireylerin beden imajlarına yönelik yoğun bozuklukları vardır. Kendilerine dışarıdan baktıklarında tıpkı ilk bakan göz gibi kusurlu olarak algılarlar bedenlerini. Beden algısındaki bozukluk, sosyal işlevlerinde bozulması ile bir kısır döngüye girer.' },
      { t: 'p', text: '“Yetersizlik” obezite sarmalındaki bir diğer durumdur. Bu yetersizlik en başta anne-bebek ilişkisinde görülür. Anne ne yaşıyorsa, bebek bunu bedenine hapsolmuş bir şekilde deneyimler. Anne bebeği kendi yetersizliğinden dolayı ya aşırı besler ve çocuk doyduğunun farkına varmaz ya da annenin ihmalkârlığı nedeniyle bebek yiyecekle karşılaştığında annenin boşluğunu doldurmak için durmadan yer. Obezite ile mücadele eden bireylerdeki “tıkanırcasına yeme (binge eating)” bu dönemden temel alır. Yoğun yetersizlik hissi ile dünyada var olabilmek oldukça zordur. Kişi gittikçe ruhsal olarak küçülürken buna bağlı dünyada fiziksel olarak daha fazla yer kaplamaya başlar. Fiziksel olarak yer kaplamak, ruhsal olarak yapılamayanın sağlıksız olan kısmıdır. Yetersizlik aynı zamanda önce acı veren duyguların hissedilmesine karşı toleransı azaltırken, sonra tüm alanlara yayılır ve kişi hiçbir duygusunu kucaklayamaz hale gelir. Obez bireylerin çoğu çok üzgün bir olaydan bahsetseler bile gülerek ve sanki neşeli şeylerden bahsediyorlarmış gibi anlatırlar. Bu da duyguların iç içe geçmesinin ve kabul edilememesinin bir göstergesidir.' },
      { t: 'h3', text: 'Obezitenin Sağlıklı Tedavisi İçin' },
      { t: 'ol', items: [
        'Ruhsal Boşaltım: Obez bireyler an’da kalmakta, “şimdi ve burada” olmakta zorluk çekerler. An’dan kopuk olmak, iletişimi güçleştirirken duyguları fark etmek ve ifade etmede zorluğu da peşinden getirir. Sadece sözel olarak ifade etmeye dayalı olan terapi yöntemleri bu anlamda süreci yavaşlatabilir ya da yetersiz kalabilir. Obez bireylerin terapisi için eylem metodu içeren “psikodrama ya da sanat terapisi” formatındaki terapi metodları daha işlevseldir. Hareket ederek çalışmak, duygusal olarak rahatlamayı beraberinde getirirken kişinin ruhsal boşaltım yapmasını sağlar.',
        'Başkası Olma: Kişinin kendi bulunduğu rolden çıkarak “öteki” olması, yeni bir bakış sağlarken kendine ait olmayan duyguların fark edilmesini ve bırakılmasını sağlar. Kişi başkası olduğunda kendine, bedenine tarafsız bir göz ile bakabilme cesaretine sahip olur. En önemlisi de içinde bulunduğu bedenden çıkıp kendine bakma imkânı sağlayan “başkası olma”, beden algısının da düzelmesini sağlar.',
        'Yemeğe Yönelmeyi Sağlayan Faktörlerin Keşfedilmesi: Kişinin tüm psikolojik alt yapısını keşfetmesi, yemeğe sadece “fiziksel bir faktör” olarak bakmaması; tıkanırcasına yeme ataklarını azaltan ve ortadan kaldıran bir süreçtir.',
        'Duyguların Kucaklanması: Tüm duyguların öncelikle “derinlemesine” hissedilmesi gerekir. Özellikle terapi sürecinde kişinin yoğun ağlamaları çok işlevseldir. Kişinin duygularını kabul ediyor olması ve ağlamak gibi yaşantılaması, istenilmeyen duyguların rahatsız edici etkilerini ortadan kaldırır.',
        'Problem Çözme Becerilerinin Gelişmesi: Yaşanılan zorlukların bedene bastırılmadan çözüme kavuşturulacak “baş etme stratejilerinin” öğrenilmesini içerir. “Hayır” diyebilme gücüne sahip olmak bu anlamda önemli diğer faktördür.',
        'Kişinin Kendisini Özel Hissetmesi ve Gücünü Fark Etmesi: Tüm erken dönem takılmaları sonucunda gelişen kendini “yetersiz, değersiz” algılamalarının bedende imaj bozukluğu yaratmasının karşıtı olarak “biricik ve sadece kendi o olduğu için” özel hissetme duygusunu deneyimlemesi kişi için son derece önemlidir.',
      ] },
    ],
  },
  {
    slug: 'ofke-duydugumuz-bir-kimseyi-asla-terk-edemeyiz',
    title: 'Öfke Duyduğumuz Bir Kimseyi Asla Terk Edemeyiz',
    category: 'makaleler',
    excerpt:
      'Kişiler “yaşam senaryosunu” önceki nesillerden devralıp sanki kendi yazgısıymış gibi sahiplenirler. Altta yatan asıl korku, hem kendimizin hem de çocuklarımızın sosyal tecride uğraması ve reddedilmesidir…',
    date: '28 Şubat 2021',
    readTime: 5,
    theme: 'deep',
    variant: 3,
    content: [
      { t: 'p', text: 'Kişiler “yaşam senaryosunu” önceki nesillerden devralıp sanki kendi yazgısıymış gibi sahiplenirler. Yerini aldığımız aile bireylerine ait fiziksel rahatsızlıkların hissedilmesi ve yaşanmasına da oldukça sık rastlanır. Ait olduğumuz sosyal grubun değerlerini öğrenme ve onları uygulama isteğimiz, hayatta kalma güdümüzle birebir bağlantılıdır. Altta yatan asıl korku, hem kendimizin hem de çocuklarımızın sosyal tecride uğraması ve reddedilmesidir. Reddedilmek, arka planda, kişi farkında olmasa da ölüm anlamına gelir. Annemiz, babamız, atalarımız yaşamla bağımızdır. Onlar hakkında hissettiklerimiz yaşam hakkında hissettiklerimizdir. Fiziksel boyuttaki kaynağımızı temsil ederler ve bunu hepimiz bir şekilde biliriz. Etkisi ister olumlu ister olumsuz olsun, bu anlayış herkese derinden dokunur.' },
      { t: 'p', text: 'Tüm kişisel olgunlaşma ve bireysel gelişim çalışmalarının temel ilkesi, kişilikte reddedilip dışlanmış ne varsa ortaya çıkarıp kabul edilmesini sağlayarak yürekte bunlara yer açmaktır. Aynı şekilde, önceki nesillerde dışlanmış aile bireylerinin de aileye dahil edilmesi, tanınması ve sevgiyle anılmasını gerekmektedir. Bu ilkenin özünde kavranması gereken, reddettiğimiz şeyin reddedildiği sürece büyük güce sahip olduğudur. Reddetme çabamız reddedilenin güçlenmesine ve bizi izlemesine neden olur. Hortlak sandığımız şey, onun hortlak olduğuna inanmamızdan güç alarak peşimizi bırakmaz. Onun rüzgârda sallanan bir örümcek ağı olduğunu keşfettiğimizdeyse korku geçer. Bakmaya tahammül edemediğimiz şeye bir kere “evet” deyip de baktığımızda, içimizde bir şeyler değişir. Bu sabit bir kabullenme değildir. Aynı zamanda korktuğumuz hortlaklara kendimizi açmak ve onlara duyduğumuz sevgimizle yüzleşmemiz gerekmektedir.' },
      { t: 'quote', text: 'Öfke duyduğumuz bir kimseyi asla terk edemeyiz. Öfke de, sevgi gibi bağlayıcı bir ilişkidir.' },
      { t: 'p', text: 'Başkalarıyla kurduğumuz her ilişkide aslında kendimizi keşfederiz. Bir diğerine duyduğumuz ihtiyaç, kendi bireyselliğimizde sahip çıkmadığımız parçalarımızı keşfetmeye ve kendi bütünlüğümüze duyduğumuz ihtiyaçtır. Aslında diğeri yoluyla kendimizle ilişki kurarız. Bastırdığımız, sakladığımız ve keşfedilmemiş tüm yönlerimizi sevmeyi ve onlara sahip çıkmayı öğreniriz. Kendi bütünlüğüne ulaşmış bireyler olduğumuzda diğerlerine duyduğumuz bağımlılık azalır, hatta belki tamamen ortadan kalkar. O zaman sevgi bir ihtiyaç veya bağımlılık olmaktan çıkar ve yeni bir nitelik kazanır. Gelişmemiz için iki şey gereklidir: bir başkasına ihtiyaç duyduğumuzun farkına vararak yakın ilişkinin zorluklarına hodri meydan demek ve bunu yaparken anlayışımızı ve sevgimizi ilişkinin bilinen boyutunun ötesine taşımak.' },
      { t: 'p', text: 'Kalıcı mutluluğun ise tek yolu vardır: Mutluluğum dışarıya, dış dünyanın arzularımı yerine getirip getirmeyişine mi bağımlı, yoksa kendi içimden mi filizleniyor? Eğer dış dünyaya bağlıysa mutluluğum geçici olacaktır; eğer varlığımın doğal bir niteliğindeyse, özgün olarak bana aittir.' },
    ],
  },
  {
    slug: 'yoksa-travmaniz-mi-var',
    title: 'Yoksa Travmanız mı Var?',
    category: 'makaleler',
    excerpt:
      'Travma, anksiyete, depresyon, kaygı bilmem ne bilmem ne… Acı çeken ruhun ilacını bilemediğimizde arkasına sığındığımız kategoriler. Hatta uğruna cilt cilt kitaplar yazdığımız.',
    date: '7 Mart 2021',
    readTime: 3,
    theme: 'rose',
    variant: 4,
    content: [
      { t: 'p', text: 'Travma, anksiyete, depresyon, kaygı bilmem ne bilmem ne… Acı çeken ruhun ilacını bilemediğimizde arkasına sığındığımız kategoriler. Hatta uğruna cilt cilt kitaplar yazdığımız.' },
      { t: 'p', text: 'Sahi nedir travma? Travması olan insan olur mu? Anne terliği, hiçbir zaman saç okşamayan baba, yetersiz hissettiren öğretmen, zorbalık yapan arkadaş, istismarcı amca… Hangimizin hayatına uğramadılar? Neye göre kategorilendireceğiz çektiğimiz acıları? Şunu yaşamışsak bu, bunu yaşamışsak bu mu diyeceğiz kendimize? Acı aynı acı değil mi?' },
      { t: 'p', text: 'Duyuldunuz mu hiç? Anlaşıldınız mı? Gerçekten koşulsuz sevildiğinizi hissettiniz mi? Cevabınız “hayır” ise bunlar da travmatik değil midir?' },
    ],
  },
  {
    slug: 'mideye-giden-yolda-psikolojik-destek',
    title: 'Mideye Giden Yolda Psikolojik Destek',
    category: 'makaleler',
    excerpt:
      'Mideye giden yolun “ruh”tan geçeceğini hiç düşünmüş müydünüz? Ruhumuz, bilinçdışımız, psikolojik dünyamız ne derseniz artık tüm hayatımızı belirleyen yegâne şey.',
    date: '14 Mart 2021',
    readTime: 4,
    theme: 'sand',
    variant: 0,
    content: [
      { t: 'p', text: 'Mideye giden yolun “ruh”tan geçeceğini hiç düşünmüş müydünüz? Ruh’tan geçmeyen şey var mı? Ruhumuz, bilinçdışımız, psikolojik dünyamız ne derseniz artık tüm hayatımızı belirleyen yegâne şey. Kıyafet tercihimizden eş seçimimize, aldığımız kilolardan alamadığımız kilolara kadar her şey psikolojik süreçlerle bağlantılı. Farkında olduğumuz ya da olmadığımız tüm yaralar kanarken başka yerlerden belli ederler kendilerini.' },
      { t: 'p', text: 'Pek çok tercihin psikolojik boyutu gelişen sosyal medya aracılığı ile bilinirken, beslenme üzerinde çok durulan bir konu değildir maalesef. Beslenme küçücük bir çocuğun annesi ile olan ilişkisinin temel göstergelerinden biriyken, biz yetişkinlerin de perde arkasına ittiğimiz süreçlere ayna tutan bir değişkendir. Durmadan yemelerimiz, tıkanırcasına yemelerimiz, yememelerimiz çok eskilerden getirdiğimiz birikimlerimizin sonucu. Ruhumuzu doyurmak için karnımızı doyurma alışkanlıklarımız mesela… Yerken neyi ve neden yediğimizin farkında mıyız?' },
      { t: 'p', text: 'Psikolojik destek alanında beslenme psikolojisi ile çalışma genellikle kişinin “neyi yediği”, “kimi yediği” ya da “yemeği reddederken aslında kime sırtını döndüğünün” aydınlatılması ile ilerler. Kişi önce temel perde arkası süreçlerin farkına vararak kendi dünyasını aydınlatır, farkındalık ile birlikte değişim gelir. Önce yara iyileşir, sonra ruh değişir…' },
    ],
  },
  {
    slug: 'cocugun-dunyasindan-anne',
    title: 'Çocuğun Dünyasından “Anne”',
    category: 'makaleler',
    excerpt:
      '“Acılar içindeyim, üşüyorum. Ne olduğunu anlayamıyorum. Çok rahat bir yerlerdeydim. Yumuşacık, sıcacık, sessiz. Şimdi hiç öyle değil. Az kalsın boğuluyordum…”',
    date: '21 Mart 2021',
    readTime: 8,
    theme: 'teal',
    variant: 1,
    content: [
      { t: 'quote', text: 'Acılar içindeyim, üşüyorum. Ne olduğunu anlayamıyorum. Çok rahat bir yerlerdeydim. Yumuşacık, sıcacık, sessiz. Şimdi hiç öyle değil. Az kalsın boğuluyordum. Nereye fırlatıldım böyle? Burası neresi? Korkunç bir gürültü var. Gözlerimi acıtan bir parlaklık. Hareket eden ışıklar var, renkli. Nedir bunlar? Çok korkuyorum. Az önce çıktığım yere dönmek istiyorum. Bu kadar görüntüye ve bu kadar gürültüye katlanamıyorum. En iyisi görmemek, duymamak: uyumak. Çok iyi uyuyunca rahatlıyorum.' },
      { t: 'quote', text: 'Neden olduğunu bilmediğim bir sıkıntı başladı yine. Müthiş bir korku. Bu neresi olduğunu bilmediğim yeni yerde var olmamı tehdit edici bir şey bu. Bağırıyorum. Avazım çıktığı kadar. O da ne? Bir şeyler hissediyorum. Adlarını daha sonra öğreneceğim dudaklarımda ve ağzımda… Bir de tenimde yeniden hissettiğim bir sıcaklık. Hemen dudaklarımın arasına alıyorum o yumuşak şeyi. Ağzımı dolduruyor. Daha çok almak istiyorum. Çekiyorum içime. Gırtlağımdan aşağılara ılık bir şeyler süzülüyor. Çok güzel kokuyor. Büyük bir haz duyuyorum. Az önceki büyük sıkıntı ve korkum geçmeye başlıyor. Yine sonradan öğreniyorum ki karnım doyuyor. Ağzıma aldığım şey bir memeymiş, gırtlağımdan süzülen de süt. Bunların hepsinin adlarını ve ne olduklarını hep sonradan öğreniyorum. Ama bildiğim bir şey var ki bana çok güzel duygular yaşatıyorlar, korkularımı gideriyorlar, beni çok rahatlatıyorlar. Emmek ve ardından uyumak öyle güzel ki.' },
      { t: 'quote', text: 'Bu hep böyle yinelenip duruyor. Ne zaman acı çekmeye başlasam, sıkıntı ve korku duysam tenimde gezinen ve sarıp sarmalayan o hoş sıcaklık. Bir de içime aldıklarım. Ağzımda hissettiğim o müthiş hisleri tarif bile edemem. Yavaş yavaş bunlar olurken bir görüntü de dikkatimi çekmeye başlıyor: bir yüz. Yaşamımı tehdit eden acılarım, açlığım, korkularım geçerken, ağzıma ve içime aldıklarımla o büyük hazları yaşarken hep aynı görüntü duruyor karşımda. Tüm bu güzellikleri yaşayabilmem için biraz bağırmam gerekiyor önce. Bazı zamanlar biraz fazlaca ve uzun bağırmam gerekiyor. Bir türlü gelmek bilmiyor o keyifli anlar. Tam da çok acı çektiğim ve çok bağırdığım bir sırada oluyor yine. Tenimde, dudaklarımda hissettiklerimle birlikte karşımda o yüz. Tam doymaya başladığımı hissediyorum ki birden acılarım, açlığım, sıkıntı ve korkularım tekrar bastırıyor. Niye bu kadar kısa sürüyor anlamıyorum. Ama o sırada tekrar görüyorum o yüzü. Bu sefer gerçekten doyuyorum ve uykuya dalabiliyorum. Demek ki az önceki gerçek değildi. Kaç kez tekrarlandıktan sonra bunu ancak anlayabildim. Sadece hayal etmişim. Hayal ettiğimle bir süreliğine doymuşum. Demek ki bir iç var, içim; hayallerim oradan besleniyor, içe attıklarımdan; ama bunlar gerçek değil, çünkü gerçekten ihtiyaçlarımı karşılamıyor, bir süre için yatıştırıyor. Bir de gerçekten doyuran var, o dışarıdan geliyor. Demek ki bir iç var, bir de dış. İçim ve dışım. Yani bir ben varım, bir de benim dışımdakiler. Bağırdığım zaman benim dışımdan bir şey geliyor, memesi, sütü ve yüzü olan. Benim dışımda bir varlık. Ona dokunabiliyorum. Onu hissedebiliyorum. Tenimde onun dokunuşlarını hissediyorum. Arada bir de hem dokunduğumu, hem dokunulduğumu hissediyorum. Aaa evet, bu benim. Kendime dokunuyorum. Bir kez daha anlıyorum beni ve benim dışımı. Kendimi hissediyorum. Beni dışarıdan ayıran bir tenim var. Dışarıdaki her şey ona değdikçe hissediyorum. Böylece sınırlarımı keşfediyorum. Bedenimin sınırlarını. Bir bütün olarak derim beni sarıyor, dışımla içimi ayıran bir hat oluşturarak ayrı bir varlık olarak beni tanımlamama yardımcı oluyor. Tabi bana dokunanların yardımcılığını da inkâr edemem.' },
      { t: 'quote', text: 'Ne zaman sıkıntı, acı, korku yaşasam onu görüyorum. Anne denilen o muhteşem varlığı. O geliyor ve tüm acılarım bir süre sonra diniyor. Tüm ihtiyaçlarımı karşılıyor. Sarıyor, sarmalıyor, ısıtıyor, yatıştırıyor, doyuruyor, zevk veriyor. Tamamen hayatım ona bağlı. Ona bağımlıyım, ona mecburum. O olmadan yaşayamam. Tam da bu nedenle ondan nefret ediyorum aynı zamanda. O her şeye sahip. Cömert, kocaman memeleri var. İçi sütle dolu. Beni sarıp sarmalayan güçlü kolları, sıcacık teni… Onun yanında öyle çaresiz bir halim var ki. Bu çaresizlik beni deli ediyor. Öfkeyle ısırıyorum memelerini.' },
      { t: 'quote', text: 'Bu arada emmekten aldığım zevkte doruğa ulaştı. Öyle güzel ki, parmağımı da emmeye başladım. Meme yeterli olmayınca alıyorum parmağımı ağzıma, emerek uyuyorum…' },
    ],
  },
  {
    slug: 'panik-atak',
    title: 'Panik Atak',
    category: 'makaleler',
    excerpt:
      'Panik kelimesi Yunan mitolojisindeki yalnız yaşayan, üzgün olduğu zamanlarda bir mağaraya kapanan, rahatsız edildiğinde çığlıklar atarak korkutan bir Tanrı’nın — Pan’ın — isminden gelmektedir.',
    date: '28 Mart 2021',
    readTime: 7,
    theme: 'night',
    variant: 2,
    content: [
      { t: 'p', text: 'Panik kelimesi Yunan mitolojisindeki yalnız yaşayan, üzgün olduğu zamanlarda bir mağaraya kapanan, rahatsız edildiğinde çığlıklar atarak korkutan bir Tanrı’nın ismi olan “Pan”dan gelmektedir. İsmin hikâyesi ile panik atak durumu elbette tesadüf değildir. Panik atak tam da böyle bir şeydir. Bilinç seviyesinde veya bilinç dışında kişinin üzüldüğünde, stresli yaşam deneyimlerinde bedeninin çığlıklar atması ve korkmasıdır.' },
      { t: 'p', text: 'Panik atak çok sık rastlanan bir kaygı durumudur. Belirtilerin şekli ve şiddeti kişiden kişiye göre değişmektedir. Önce panik atak belirtilerine bakalım:' },
      { t: 'ol', items: [
        'Çarpıntı, kalp atımlarını duyumsama ya da kalp hızında artma olması',
        'Terleme',
        'Titreme ya da sarsılma',
        'Nefes darlığı ya da boğuluyor gibi olma duyumları',
        'Soluğun kesilmesi',
        'Göğüs ağrısı ya da göğüste sıkıntı hissi',
        'Bulantı ya da karın ağrısı',
        'Baş dönmesi, sersemlik hissi, düşecekmiş ya da bayılacakmış gibi olma',
        'Kontrolü kaybedeceği ya da çıldıracağı korkusu',
        'Ölüm korkusu',
        'Uyuşma veya karıncalanma',
        'Üşüme, ürperme ya da ateş basmaları',
      ] },
      { t: 'p', text: 'Panik atak, dayanılması zor belirtileri içinde barındırır. Kişi sürekli olarak bu belirtilerin ortaya çıkacağı korkusunu yaşar ve bu sebeple özellikle ilk belirtiyi yaşadığı durumlardan ve ortamlardan kaçınır.' },
      { t: 'p', text: 'Panik atak belirtileri Tanrı Pan’ın üzüldüğünde çığlık attığı çığlıkların bedende karşılık bulmasıdır. Deneyimlenmesi zor olan bu belirtiler kişinin yaşadığı deneyimleri duymaması-fark etmemesi sonucunda bedeninin dile gelmesidir aslında. Bizler yaşadığımız şeylerin hemen ortadan kalkması için çaba gösterir, doktor doktor gezer, bir sürü psikoloğa gider, farklı terapiler-ilaçlar deneriz. Bedenimizin çığlığına kulak vermeyiz. Bedenimiz ne oluyor da bu şekilde zangır zangır, bizi korkudan öldürürcesine bağırıyor? Bugün yanınızda biri bağırmaya-ağlamaya başladığında ona nasıl tepki verirsiniz? Sus-kes sesini mi dersiniz? Neler oluyor? İyi misin diye sorar mısınız? Peki ya bedenimize? Bedenimizin bu çaresizce çığlıklarına soruyor muyuz? Sana — dolayısıyla bana — ne oluyor? Diye.' },
      { t: 'p', text: 'Panik atak gibi belirtilerin ortaya çıkmasının en yaygın sebeplerinden biri “kişinin kendi duygularının farkında olmamasıdır”. Sadece yaşayan, duyguları üzerine düşünmeyen bireyler dolayısıyla bunları ifade de edemezler. Sonsuz bir enerji ve duygu birikimi kişinin bedeninde sıkışıp kalır. Üzüldüğümüzde-korktuğumuzda bunun üzerine düşünmek yerine bu duyguların hemen geçmesini diler ve onları bastırırız. İfade etmemiz bile ya öfkeyle olur ya da dilimizden dışarıya çıkmaz. Olumsuz duyguların deneyimlenmesi zordur ve özellikle panik atak durumu yaşayan bireyler için korkunçtur. Bu duyguları deneyimlemekten sürekli kaçarlar.' },
      { t: 'p', text: 'Panik atak yaşayan bireylerde en çok görünen duygulardan biri de “suçluluk” hissidir. Bilinçli veya bilinçsiz şekilde olaylara-yaşantılara-kişilere karşı yoğun olarak suçluluk hissederler.' },
      { t: 'p', text: 'Suçluluk hissi, kişinin fark edilip anlamlandırılmadığında kişinin bedenine-yaşamına büyük darbe vuran hislerden biridir. Suçluluk aslında içe dönmüş öfkedir. Kişiyi gittikçe depresif ve değersiz hissettirir. Kişinin kendi dışında gelişen olaylardan bile kendisini suçlamasına, yeryüzündeki bütün olumsuz şeylerin onunla ilgili olduğunu hissetmesine sebep olur. Bu kişiler hayattan zevk almak konusunda çok zorlanırlar. İyi şeyleri hiç üzerlerine almazlar, kötü olan her şey ise benliklerine yapışıp kalır.' },
      { t: 'p', text: 'Özet olarak panik atak; kişinin kendini duymaması, olumsuz duyguları yaşamaktan kaçması, yaşadıkları üzerinde bir anlam bulunmaması ve bedenin çığlıklar atması halidir. Amacımız bedeninin çığlıklarına kulak vermek ve onu dinlemektir. Duyulan beden ne ağrır, ne acır ne de panik atak geçirir.' },
      { t: 'h3', text: 'Panik Atak Sürecinde Neler Yapalım?' },
      { t: 'p', text: 'Panik atak belirtilerinin tekrar gelmesi-yaşanması korkusu bireyler için çok büyük bir kaygı kaynağıdır. Bazı kişilerde bu belirtiler tekrar eder, bazılarında birkaç kez yaşanır ve ortadan kaybolur. Tekrar eden panik atak belirtilerinde bedenin sesini duymak önemlidir. Panik atak belirtileri asla “rastgele” olmaz. Belirtileri ortaya çıkartan “stres yaratan bir uyaran, tetikleyici bir şey” mutlaka vardır.' },
      { t: 'p', text: 'Belirtiler ortaya çıkınca dikkat etmemiz gereken şeyler;' },
      { t: 'ol', items: [
        'Bilinenin aksine o anda belirtileri yok etmek veya geçirmek için uğraşmayın. Şöyle düşünelim; şu anda size “mavi bir fil düşünmeyin sakın!” dediğimde aklınıza hemen mavi bir fil gelecektir. Panik atak belirtilerini yok etmek de böyledir. Atak anında geçirmek için yaptığınız eylemler sizi ataklara hapseder. Atak anında gelen belirtilerinizin daha fazla içine girin. Örneğin; nefes alamıyormuş gibi hissettiğinizde derin derin nefes almaya çalışmak yerine, göğsünüz sıkışıyorsa o sıkışmaya odaklanın, başınız dönüyorsa baş dönmenize odaklanın. Yok etmeye çalışmayın. Belirtilere odaklanmak, bedeninizin sesini duymanızı sağlayacaktır. Sesi duyulan beden yavaş yavaş sesinin şiddetini kısmaya başlar.',
        'Panik atak asla “durup dururken” ortaya çıkmaz. Bir film, bir bakış, ses, koku vb. birçok şey ruhsallık üzerinde tetikleyici olabilir. Panik atak geldiği anda veya belirtiler ortadan kalktığında üzerine düşünmek lazım. Tetikleyici ne oldu? Bu tetikleyici benim bedenimin neden çığlık atmasına neden oluyor?',
      ] },
      { t: 'p', text: 'İster panik atak, ister başka bedensel süreçler olsun. Bedenimizin neden tepki verdiğini bulmak hayatımız için en büyük kazanım ve şifa olacaktır. Anılar ve rüyalar, belirtilerin nedenleri hakkında çok önemli bilgiler verir.' },
      { t: 'p', text: 'Özetle panik atak belirtilerinden korkmak yerine onları kucaklamak, geldiğinde kendimiz hakkında önemli bilgiler edinmek için bedenimizin bize verdiği fırsatı değerlendirmek gerekir. Farkındalık en büyük şifadır.' },
    ],
  },
  {
    slug: 'belirtileri-cocuklarin-elinden-almayalim',
    title: 'Belirtileri Çocukların Elinden Almayalım',
    category: 'makaleler',
    excerpt:
      'Çocuklar dil becerileri gelişmeden önce bedensel belirtilerle duygularını ifade ederler. Bebek ağlar anne altını değiştirir, bebek ağlar anne emzirir.',
    date: '4 Nisan 2021',
    readTime: 5,
    theme: 'terra',
    variant: 3,
    content: [
      { t: 'p', text: 'Çocuklar dil becerileri gelişmeden önce bedensel belirtilerle duygularını ifade ederler. Bebek ağlar anne altını değiştirir, bebek ağlar anne emzirir. Hislerimizi, duygularımızı, yaşadıklarımızı bedensel belirtilerle dışa vurmak daha anne rahmindeyken öğrendiğimiz bir şeydir. Büyükçe fark ettiğimiz veya etmediğimiz duygularımızı da bedensel belirtilerle dışa vururuz. Bu aynı zamanda yaşanan duygunun yatıştırılması, boşaltılması ve dışarıya ifade edilmesidir.' },
      { t: 'p', text: 'Altını ıslatan, tırnak yiyen, saçlarını yolan, bol bol hastalanan, parmak emen vb. gibi belirtiler gösteren çocuklar da duygularını bize bedensel şekilde ifade ediyorlar. “SEVGİLİ ANNE-BABA/ÖĞRETMENLER/DIŞ DÜNYADAKİ YETİŞKİNLER, içimde tanımlayamadığım duygular var, ben bu duyguları anlamlandıramıyorum, bu duygular minik bedenime ve ruhuma fazla geliyor, siz bu belirtilerle beni anlayın” diyor çocuklar.' },
      { t: 'p', text: 'Çocukların bu belirtilerine bir an önce kurtulmamız gereken başımızın belası durumlar olarak değil, çocuğun bize ifade etmek istediği bir şeyler var diye bakmalıyız. Tırnak yiyen çocuğun ellerine acı oje sürmek herkes için tanıdık bir durumdur. Ne yapıyoruz bu davranışımızla? Çocuğun “ben bir şeyler hissediyorum” dediği dili onun elinden alıyoruz. Bedensel belirtiler çocuğun dilidir. Belirtileri çocukların ellerinden almamalıyız. Bu hem çocuğun ifade dili hem de çocuğun duygularını düzenleme sürecidir. Bizler hem çocuğun ifade dilini elinden alıyoruz, hem de yaşadığı duyguyu düzenlemesi için bulduğu yolu yok ediyoruz. Hiç çocuğun ne yaşadığına odaklanmıyoruz, üzerine düşünmüyoruz.' },
      { t: 'p', text: 'Çocuk kliniğinde özellikle tırnak yeme ve alt ıslatma problemleri çok yaygındır. Bu güne kadar gördüğüm tüm ebeveynler bu belirtilerin yok olması için çocuklarını getirdiler. Hiçbir ebeveyn “çocuğum bunları yapıyor ama acaba neden? Nedenini bilmek istiyorum” diye sormadı. Tek istenilen bu belirtilerin yok olması. Ne kadar büyük haksızlıklar yapıyoruz çocuklarımıza, ne kadar duymuyoruz, üzerine düşünmüyoruz. Evimize gelen misafirlere sonsuz ilgi, şefkat gösterirken; henüz dünyamızda birkaç senedir var olan, evimize yeni gelmiş olan bu minik misafirlere neden böyle davranıyoruz?' },
      { t: 'p', text: 'Çocukların bedensel belirtileri ortadan kaybolsun diye psikoloji literatüründe pek çok yöntem var. Koskoca psikoloji literatürü bile yıllar boyunca çocukların bedensel belirtileri yok olsun diye yol ararken, yeni yeni “acaba bu belirtiler ne anlama geliyor” diye düşünmeye başladı.' },
      { t: 'quote', text: 'ÇOCUKLARIN BELİRTİLERİNİ ELLERİNDEN ALMAYALIM, ÜZERİNE DÜŞÜNELİM. BİZİM ÇOCUKLARIMIZA NE OLUYOR?' },
    ],
  },
  {
    slug: 'cocuklar-icin-degiselim',
    title: 'Çocuklar İçin Değişelim',
    category: 'makaleler',
    excerpt:
      'Çocuklara bakışımız, temasta bulunurken kullandığımız dil ve beden hareketlerimiz, dünyamızda henüz birkaç senedir bulunan ve her şeyi yeni keşfeden küçük bireyler için çok önemlidir.',
    date: '11 Nisan 2021',
    readTime: 8,
    theme: 'sand',
    variant: 4,
    content: [
      { t: 'h2', text: 'Çocuklar İçin Değişelim – 1' },
      { t: 'p', text: 'Çocuklara bakışımız, temasta bulunurken kullandığımız dil ve beden hareketlerimiz, dünyamızda henüz birkaç senedir bulunan ve her şeyi yeni keşfeden küçük bireyler için çok önemlidir. Fiziksel şiddet ve fiziksel istismarı bir kenara koyarak düşünelim, bizim bugüne kadar ki tüm yaralarımız “ötekinin” kullandığı dil yüzünden olmadı mı? Duyduğumuz “beceriksiz, aptal, özgüven eksikliği var sende, gebertirim seni, sen yapamazsın, buna mı üzüldün, ağlayacak ne var? vb.” gibi söylemler hayattaki en büyük travmalarımız, yaralarımız olmadı mı? Biz “dil” ile yaralanıyoruz. Ne ilginçtir ki ellerinde “dil” dışında hiçbir başka materyal olmayan terapistler de “dil” ile iyileştirmeye çalışıyor. O zaman bu sene “ebeveyn-çocuk yılı” kapsamında dilimizi değiştirelim. Emin olun ki değiştirdiğimiz her terim, her davranış mutlaka çocuklara şifa olacaktır. Bugünün şifalanan çocukları geleceğin sağlıklı yetişkinleri olacak. Haydi kolları sıvayalım! Değiştirdiğiniz her dil ile ilgili örnekleri bizi etiketleyerek yayabilir ve birçok insanı cesaretlendirebilirsiniz.' },
      { t: 'h3', text: 'Özgüven Eksikliği Değil / Yetersiz Hissettiği Alanlar Var' },
      { t: 'p', text: 'Bir çocuk için “özgüven eksikliği” terimi, çocuğun tüm benliği için yetersizlik ifade eder. Sanki çocuğun bu hayatta yeterli olduğu, iyi yapabildiği hiçbir şey yokmuş gibi! Mümkün mü? Çocuk gibi hayal gücü sınırsız, yaratıcılık kapasitesi sonsuz olan birey için benliğinin bu kadar eksikmiş gibi düşünülmesi?' },
      { t: 'p', text: 'Her bireyin “yeterli hissettiği-yeterli olduğu” ve “yetersiz hissettiği-yeterli olamadığı” alanlar vardır. Bu çocuklar için de geçerlidir. Bazı çocuklar okumayı hızlı öğrenir, bazılarının yazısı çok güzeldir, bazısı sporda iyidir, bazısı iletişimde, bazısı sanatta… Bazısı okumayı çok geç sökecektir, bazısının yazısı çok kötüdür, kimi resim yapmaktan hiç anlamaz, bazısı sakardır…' },
      { t: 'p', text: 'Her çocuğun iyi yaptığı veya tam istediği gibi yapamadığı bir dünya şey vardır. Tüm bunları topladığımızda “özgüven eksikliği var” diye bir çocuğun bütün benliğinin eksik-yarım olduğunu asla söyleyemeyiz.' },
      { t: 'quote', text: 'ÖZGÜVEN EKSİKLİĞİ OLAN ÇOCUK YOKTUR, ÇOCUKLARIN YETERLİ HİSSETTİĞİ ALANLAR VE YETERLİ HİSSETMEDİĞİ ALANLAR VARDIR.' },
      { t: 'h2', text: 'Çocuklar İçin Değişelim – 2: Duyulma İhtiyacı' },
      { t: 'p', text: 'Duyulmaya ihtiyaç duymak… Kulağa biraz tuhaf geliyor değil mi? Konuştuğumuz zaman duyuluyoruzdur elbette. Bu durum neden konu olsun veya ihtiyaç olsun ki?' },
      { t: 'p', text: 'Düşünelim birlikte, yetişkin halimizden düşünelim. Hayatınız boyunca birinin veya birilerinin karşısında hiç olmadığınız, kendiniz gibi davranmadığınız oldu mu? Aslında söylemek istediklerinizin tam tersini söylediğiniz oldu mu? Veya söylemek istediklerinizi daha öfkeli, daha yüksek sesli, daha abartarak ifade ettiğiniz? Söylemek istediklerinizi dolaylı yoldan, beden dilinizle, kılık-kıyafetinizle, size ait olmayan davranışlarınızla veya içeriğini gerçekdışı bir şekilde ifade ettiğiniz? İlla olmuştur. Niye böyle davranıyoruz o zaman? DUYULMA İHTİYACIMIZDAN.' },
      { t: 'p', text: 'Yemek yemek, su içmek gibidir duyulma ihtiyacı. Karşınızdaki sizi duymuyorsa varlığınız da tehlikeye düşer. Yok olursunuz. Fiziksel olarak varken, ruhsal olarak yok olmak kişide derin yaralar açar. Karşınızdaki sizi görüyor, dinliyor, konuşuyor olsa bile acınızı, kaygınızı, heyecanınızı duymuyorsa bu durum çok yaralayıcı olur.' },
      { t: 'p', text: 'Biz çocukları ne kadar görüyor veya duyuyoruz? Evin içinde veya okulda bu küçük bireyler etrafta dolanıyor, oyun oynuyor, konuşuyorlar bizde onları dinliyoruz, fiziksel ihtiyaçlarını karşılıyoruz. Peki ruhsal ihtiyaçları? Görülme-duyulma ihtiyaçları?' },
      { t: 'h3', text: 'Görebilmek-Duyabilmek İçin' },
      { t: 'p', text: 'Sözden öteyi duyabilmek, kişinin yaşadıklarını görebilmek için soru sormadan, büyüdükçe unuttuğumuz bir yetimizi hatırlamamız lazım. HİSSETMEK! Gerçekten karşımızdaki hiçbir şey söylemeden hissetmek. Evdeki çocuğu, terapi koltuğundaki danışanı, yanımızdaki eşimizi “hissetmemiz” için ise ilk önce kendimizi duymamız ve hissetmemiz lazım. Sahi biz kendi duygularımızı, travmalarımızı, öfkemizi ne kadar hissediyoruz, yaşantılıyoruz, iyileştirmek için çabalıyoruz? Biz kendimizi duyuyor muyuz ki bir çocuğu veya ötekini duyalım? Kulaklarımız kendimize sağırken bir başkasını duyamayız. Ebeveynlerin en çok zorladığı süreçlerden biri de maalesef bu duyulmamak meselesinden geliyor.' },
      { t: 'p', text: 'Bizler gibi çocuklar da görülmek ve duyulmak isterler. Hayat üzerinde hiçbir kontrolleri olmayan bu küçük bireyler, söylediklerinin ve yaptıklarının ötesindeki davranışlarının, duygularının duyulmasına ihtiyaç duyarlar.' },
      { t: 'p', text: 'Bir çocuğun görülme ve duyulma ihtiyacını ona soru sormadan, yüz ifadesini, beden dilini okuyarak ve ifade ederek karşılayabiliriz. Okuldan eve gelen çocuğa “günün nasıl geçti” diye sorduğunuzda cevap alamazsınız. “İyi”, “oyun oynadım” gibi söylemlerde bulunurlar. Gün boyunca çocuğun yaşadığı kaygıdan, korkudan haberimiz olmadan, onu duymadan hayata devam ederiz. Yetişkinler olarak hep dilden çıksın isteriz ne varsa, fakat özellikle çocuklar dil gelişimleri sebebi ile duygularını, yaşadıklarını bedensel belirtilerle ifade ederler. Çocuğu iyi tanımak önemlidir. Hangi duyguda bedeni nasıl görünüyor? Yanakları kızarınca hangi duyguyu yaşamış oluyor? Tırnaklarını hangi duyguya karşılık yiyor? Kardeşine vurduğunda ne hissediyor? Bunları iyi gözlememiz, iyi koklamamız lazım. Yetişkinler içinde bu durum önemlidir. Karşımızdaki fiziksel olarak görmekten çok, duygularının bedensel karşılıklarını görmek; söylediklerini duymaktan çok cümlelerinin satır aralarını okumak önemlidir. Kendini duyan, ihtiyaçlarını gören ve daha sonra ötekini gören-duyan bireyler olmamız ümidiyle…' },
    ],
  },
];
